config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :user do
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end
  
  resource :profile, only: [:show, :update]
  
  resources :users do
    collection do
      get :search
    end
    
    get :statuses
    
    post :follow, controller: :followships, action: :create
    delete :unfollow, controller: :followships, action: :destroy
    
    post :block, controller: :blocks, action: :create
    delete :unblock, controller: :blocks, action: :destroy
  end
  
  resources :statuses, only: :create do
    resources :replies, only: [:index, :create]
  end
  
  resource :timeline, controller: :timeline, only: [] do
    get :statuses
    get :recents
  end
  
  root 'timeline#show'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Plugins
  devise :omniauthable, omniauth_providers: [:twitter]
  
  # Callbacks
  after_update :remote_update_profile, if: :changed?
  
  # Class Methods
  def self.from_omniauth(auth)
    find_or_initialize_by(twitter_uid: auth.uid).tap do |user|
      user.name                        = auth.info.name
      user.username                    = auth.info.nickname
      user.description                 = auth.info.description
      user.url                         = auth.extra.raw_info.url
      user.twitter_access_token        = auth.credentials.token
      user.twitter_access_token_secret = auth.credentials.secret
      
      user.save!
    end
  end
  
  # Methods
  def client_config
    @client_config ||= lambda do |config|
      config.consumer_key        = Figaro.env.twitter_consumer_key
      config.consumer_secret     = Figaro.env.twitter_consumer_secret
      config.access_token        = self.twitter_access_token
      config.access_token_secret = self.twitter_access_token_secret
    end
  end
  
  def client
    @client ||= Twitter::REST::Client.new(&client_config)
  end
  
  def streaming_client
    @streaming_client ||= Twitter::Streaming::Client.new(&client_config)
  end
  
  def me?(screen_name)
    self.username.downcase == screen_name.downcase
  end
  
  def remote_update_profile
    self.client.update_profile \
      name:        self.name,
      description: self.description,
      url:         self.url
  end
  
  def remote_timeline(max_id = nil)
    options = { count: 10 }
    options[:max_id] = max_id if max_id.present?
    
    self.client.home_timeline(options)
  end
  
  def remote_user_timeline(user_id, max_id = nil)
    options = { count: 10 }
    options[:max_id] = max_id if max_id.present?
    
    self.client.user_timeline(user_id, options)
  end
  
  def remote_recents(count = 5)
    sample_users = []
    streaming_client.sample do |s|
      case s
      when Twitter::Tweet
        sample_users << s.user
      end
    
      break if sample_users.size == count
    end
    sample_users
  end
  
  def remote_user(username = self.username)
    self.client.user(username)
  end
  
  def remote_status(status_id)
    self.client.status(status_id)
  end
  
  def remote_follow(username)
    self.client.follow(username).first
  end
  
  def remote_unfollow(username)
    self.client.unfollow(username).first
  end
  
  def remote_search(query, count = 5)
    self.client.user_search(query, count: count)
  end
  
  def remote_blocked?(user)
    self.client.block?(user)
  end
  
  def remote_block(user)
    self.client.block(user).first
  end
  
  def remote_unblock(user)
    self.client.unblock(user).first
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def index
    if current_user.twitter_uid.in?(%w[69586833 3323417409])
      @users = User.all
    else
      redirect_to root_path
    end
  end
  
  def show
    if current_user.me?(params[:id])
      redirect_to profile_path
    else
      @user = current_user.remote_user(params[:id])
    end
  rescue Twitter::Error::NotFound => e
    redirect_to root_path, alert: "User not found: #{params[:id]}"
  end
  
  def statuses
    @statuses = current_user.remote_user_timeline(params[:user_id], params[:max_id].to_s.presence)
  end
  
  def search
    respond_to do |format|
      format.html { @users = current_user.remote_search(params[:q], 15) }
      format.json { @users = current_user.remote_search(params[:q], 6) }
    end
  end
end

app/views/users/_card.html.haml
#card
  .text-center
    = link_to user_path(user.screen_name) do
      = image_tag user.profile_image_url.to_s.gsub('_normal', ''), class: 'img-thumbnail img-responsive'
    %h1 @#{user.screen_name}
    %p= render partial: 'users/stats', locals: { user: user }
    - if user.description.present?
      %p.lead
        = twitter_text user.description
    - unless blocked || current_user.me?(user.screen_name)
      %p
        = render partial: 'shared/follow_unfollow', locals: { user: user }
        = link_to 'Block', user_block_path(user.id), method: :post, class: 'btn btn-danger', data: { disable_with: 'Blocking...' }
  .row
    .col-xs-8
      %dl
        - if user.name.present?
          %dt
            %strong Full name:
          %dd= user.name
        - if user.location.present?
          %dt
            %strong Location:
          %dd= user.location
        - if user.url.present?
          %dt
            %strong Website:
          %dd= link_to nil, user.url.to_s
    .col-xs-4
      - if current_user.me?(user.screen_name)
        .text-center
          = link_to '#', id: 'edit-profile', class: 'btn btn-link' do
            %i.fa.fa-edit
            Edit profile
          
- if current_user.me?(user.screen_name)
  #edit_user.hide
    = render partial: 'users/form', locals: { user: user }

app/views/users/_form.html.haml
= form_for :user, object: user, url: profile_path, method: :patch do |f|
  .text-center
    = link_to user_path(user.screen_name) do
      = image_tag user.profile_image_url.to_s.gsub('_normal', ''), class: 'img-thumbnail img-responsive'
    %h1 @#{user.screen_name}
    %p= render partial: 'users/stats', locals: { user: user }
    - if user.description.present?
      %p.lead
        = f.text_area :description, class: 'form-control', rows: 3, placeholder: 'Description'
  .row
    .col-xs-8
      .form-group
        = f.label :name, 'Full name:'
        = f.text_field :name, class: 'form-control', placeholder: 'Full name'
      .form-group
        = f.label :url, 'Website:'
        = f.url_field :url, class: 'form-control', placeholder: 'Website'
    .col-xs-4
      .text-center
        = f.button type: :submit, class: 'btn btn-primary' do
          %i.fa.fa-floppy-o
          Save
        %br/
        = link_to 'Cancel', '#', id: 'cancel-edit-profile', class: 'btn btn-link'

app/views/users/_list.html.haml
%li.media
  .media-left.media-middle
    = link_to user_path(user.screen_name) do
      = image_tag user.profile_image_url.to_s.gsub('_normal', '_bigger'), width: 73, class: 'media-object img-circle img-thumbnail'
  .media-body
    %h4= user.name
    %p= twitter_text "@#{user.screen_name}"
    %p
      = render partial: 'shared/follow_unfollow', locals: { user: user }

app/views/users/_stats.html.haml
%strong Tweets:
= user.statuses_count.to_i
&nbsp;
%strong Followers:
%span#followers_count= user.followers_count.to_i
&nbsp;
%strong Following:
= user.friends_count.to_i

app/views/users/_user.html.haml
- blocked = current_user.remote_blocked?(user)

.row
  .col-sm-4
    = render partial: 'users/card', locals: { user: user, blocked: blocked }
      
  .col-sm-8
    - if current_user.me?(user.screen_name)
      = render partial: 'shared/new_tweet'
    
    - if blocked
      .text-center
        %p
          %span.fa-stack.fa-5x
            %i.fa.fa-user.fa-stack-1x
            %i.fa.fa-ban.fa-stack-2x.text-danger
        %p.lead
          This user is blocked.
          = link_to 'Unblock', user_unblock_path(user.id), method: :delete
          to view his/her tweets.
    - else
      #statuses-loader
        .list-group
          .list-group-item
            .text-center
              %i.fa.fa-refresh.fa-spin.fa-lg
      .list-group#statuses{rel: :tweets, data: { refresh_url: user_statuses_path(user.screen_name, :js), loader: '#statuses-loader' }}

app/views/users/index.html.haml
%h1 Users

.table-responsive
  %table.table.table-striped.table-bordered.table-hover.table-condensed
    - user_fields = User.column_names
    %thead
      %tr
        - user_fields.each do |field|
          %th= field.titleize
    - @users.each do |user|
      %tr
        - user_fields.each do |field|
          %td= user.send(field)
    

app/views/users/search.html.haml
%h1
  Search results for
  %small= params[:q]
  
- if @users.present?
  .row
    - @users.in_groups_of(3).to_a.transpose.each do |users|
      .col-sm-4
        %ul{style: 'padding: 0;'}
          - users.each do |user|
            - if user.present?
              = render partial: 'users/list', locals: { user: user }
- else
  .alert.alert-info No users found matching your query.
      

app/views/users/show.html.haml
= render partial: 'users/user', locals: { user: @user }

app/views/users/statuses.html.haml
- if @statuses.present?
  - @statuses.each do |status|
    = render partial: 'statuses/status', locals: { status: status }
    
  .list-group-item.text-center
    = link_to 'Load more', url_for(params.merge(max_id: @statuses.last.id - 1)), class: 'btn btn-link btn-block', rel: :more