config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :user do
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end
  
  resource :profile, only: [:show, :update]
  
  resources :users do
    collection do
      get :search
    end
    
    get :statuses
    
    post :follow, controller: :followships, action: :create
    delete :unfollow, controller: :followships, action: :destroy
    
    post :block, controller: :blocks, action: :create
    delete :unblock, controller: :blocks, action: :destroy
  end
  
  resources :statuses, only: :create do
    resources :replies, only: [:index, :create]
  end
  
  resource :timeline, controller: :timeline, only: [] do
    get :statuses
    get :recents
  end
  
  root 'timeline#show'
end

app/views/shared/_follow_unfollow.html.haml
- unless current_user.me?(user.screen_name)
  = link_to 'Follow', user_follow_path(user.screen_name), method: :post, data: { disable_with: 'Following...' }, remote: true, id: "follow-#{user.screen_name}", class: "btn btn-primary#{(' hide' if user.following?)}"
  = link_to 'Unfollow', user_unfollow_path(user.screen_name), method: :delete, data: { disable_with: 'Unfollowing...' }, remote: true, id: "unfollow-#{user.screen_name}", class: "btn btn-danger#{(' hide' unless user.following?)}"

app/views/shared/_new_tweet.html.haml
.well.well-sm
  = form_for @status, remote: true, html: { id: 'new-tweet', data: { type: :json } } do |f|
    = error_messages(f)
    
    .form-group
      = f.text_area :text, class: 'form-control', rows: 3, placeholder: 'What\'s up?', autofocus: true
    
    .row
      .col-sm-9
        %p.text-danger
      .col-sm-3.text-right
        .visible-xs
          = f.button 'Tweet!', name: nil, class: 'btn btn-primary btn-block', data: { disable_with: '<i class="fa fa-circle-o-notch fa-spin"></i> Tweeting...' }
        .hidden-xs
          = f.button 'Tweet!', name: nil, class: 'btn btn-primary', data: { disable_with: '<i class="fa fa-circle-o-notch fa-spin"></i> Tweeting...' }