config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :user do
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end
  
  resource :profile, only: [:show, :update]
  
  resources :users do
    collection do
      get :search
    end
    
    get :statuses
    
    post :follow, controller: :followships, action: :create
    delete :unfollow, controller: :followships, action: :destroy
    
    post :block, controller: :blocks, action: :create
    delete :unblock, controller: :blocks, action: :destroy
  end
  
  resources :statuses, only: :create do
    resources :replies, only: [:index, :create]
  end
  
  resource :timeline, controller: :timeline, only: [] do
    get :statuses
    get :recents
  end
  
  root 'timeline#show'
end

app/views/layouts/_nav.html.haml
%nav.navbar.navbar-default.navbar-static-top
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{type: :button, data: { target: '.navbar-collapse', toggle: :collapse}}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to root_path, class: 'navbar-brand' do
        = image_tag 'logo.png'
    .navbar-collapse.collapse
      = render partial: 'layouts/session'
      = render partial: 'layouts/search'

app/views/layouts/_search.html.haml
= form_tag search_users_path, method: :get, class: 'navbar-form' do
  .form-group{style: 'display: inline;'}
    .input-group{style: 'display: table;'}
      %span.input-group-addon{style: 'width: 1%;'}
        %i.fa.fa-search
        %i.fa.fa-refresh.fa-spin.hide
      = search_field_tag :q, params[:q], class: 'form-control', placeholder: 'Search...', autocomplete: :off, dir: :ltr, rel: :typeahead, data: { remote_url: search_users_path(q: '%QUERY') }
      = submit_tag nil, name: nil, class: 'hide'

app/views/layouts/_session.html.haml
%ul.nav.navbar-nav.navbar-right
  %li
  %li.dropdown
    = link_to '#', data: { toggle: :dropdown } do
      @#{current_user.username}
      %span.caret
    %ul.dropdown-menu
      %li
        = link_to 'Profile', profile_path
      %li.divider
      %li
        = link_to 'Logout', destroy_user_session_path, method: :delete

app/views/layouts/application.html.haml
!!!
%html{lang: :en}
  %head
    %meta{charset: 'utf-8'}/
    %meta{content: 'IE=edge', :'http-equiv' => 'X-UA-Compatible'}/
    %meta{content: 'width=device-width, initial-scale=1', name: 'viewport'}/
    %meta{content: 'text/html; charset=UTF-8', :'http-equiv' => 'Content-Type'}/
    %title AutoTwittler
    = stylesheet_link_tag :application, media: :all
    /[if lt IE 9]
      = javascript_include_tag 'https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js'
      = javascript_include_tag 'https://oss.maxcdn.com/respond/1.4.2/respond.min.js'
    = csrf_meta_tags
  %body
    = render partial: 'layouts/nav'
    
    .container
      = flash_messages
      
      .row
        - if content_for?(:sidebar)
          .col-md-8
            = yield
          .col-md-4
            = content_for :sidebar
        - else
          .col-md-12
            = yield
    
    = javascript_include_tag :application
    = content_for :javascripts if content_for?(:javascripts)

app/views/layouts/guest.html.haml
!!!
%html{lang: :en}
  %head
    %meta{charset: 'utf-8'}/
    %meta{content: 'IE=edge', :'http-equiv' => 'X-UA-Compatible'}/
    %meta{content: 'width=device-width, initial-scale=1', name: 'viewport'}/
    %meta{content: 'text/html; charset=UTF-8', :'http-equiv' => 'Content-Type'}/
    %title AutoTwittler
    = stylesheet_link_tag :application, media: :all
    = stylesheet_link_tag :guest, media: :all
    /[if lt IE 9]
      = javascript_include_tag 'https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js'
      = javascript_include_tag 'https://oss.maxcdn.com/respond/1.4.2/respond.min.js'
    = csrf_meta_tags
  %body
    .site-wrapper
      .site-wrapper-inner
        .cover-container
          .inner.cover
            %h1.cover-heading
              = image_tag 'logo-guest.png'
            %p.lead
              The ultimate
              = link_to 'Twitter', 'http://twitter.com'
              client for
              = link_to 'AutoButler', 'http://autobutler.dk'
            %p.lead
              = link_to user_omniauth_authorize_path(:twitter), class: 'btn btn-lg btn-default' do
                %i.fa.fa-twitter
                %span{style: 'font-weight: normal;'} Login with
                Twitter
            = flash_messages
          .mastfoot
            .inner
              %p
                #{link_to 'AutoTwittler', root_path} &copy; #{Time.current.year}.
                Developed by #{link_to '@RaMin0', 'http://twitter.com/RaMin0'}.
    
    = javascript_include_tag :application
    = javascript_include_tag 'ie10-viewport-bug-workaround'